dist: trusty
sudo: required
language: bash
before_install:
- wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip -O /tmp/terraform.zip
- sudo unzip -d /usr/local/bin/ /tmp/terraform.zip
- wget https://github.com/wata727/tflint/releases/download/v0.9.2/tflint_linux_amd64.zip -O /tmp/tflint.zip
- sudo unzip -d /usr/local/bin/ /tmp/tflint.zip
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-05/run.sh | bash
install:
- pip install --user -r ansible/requirements.txt
- pip install ansible
- pip install --user ansible-lint

script:
- mv packer/variables.json.example packer/variables.json
- packer validate -var-file=packer/variables.json packer/app.json
- packer validate -var-file=packer/variables.json packer/db.json

- terraform fmt -check=true terraform/
- terraform fmt -check=true terraform/stage/
- terraform fmt -check=true terraform/prod/
  
- terraform validate -check-variables=false terraform/
- terraform validate -check-variables=false terraform/stage/
- terraform validate -check-variables=false terraform/prod/
 
- tflint terraform/
- tflint terraform/stage/
- tflint terraform/prod/

- ansible-lint ansible/playbooks/*.yml

notifications:
  slack:
    rooms:
      secure: CwtZaGPHkCsM3HOBpZ6/gMCbwH5rajm2vNLF4/jt7Nm1auelxK8vsPbRrNGjFGGQbmdbotxoEU3uBvdb9F1VOtorsBG63xGc9BC5djtIThA8uEKGoylyklrXbeVpvi8c4YEgmDD6OkvvnkCp/mn7xrq0Avx98jruvGtBPDL3gAQpctfgT0eOfIlydHIS/JKre046TMPLZEnHdnhxouG0qvEFT/p1ai8MA0s9q367UnWSTaYOe0yVeuRwXud/Y13aEZblnOz/w93od3dyea7M09d8YzRrzixBdQzCXngsolg3oQE0HHLR2w8DJ4kYhd0Yb5u7eLgXfso0ez22dWhK1ff5W854fqDUmMgxt7jyqeAJH1ZVGycFf5X8H4MaLSb4f3BL+mgdmSESiT1ibWnCPxq4/DntUR4EWJmDVk+GLzSo65dBrIbKZCAtxQxS9UReBl5OPXrZIluYS4FDDVzGlaGy5A5W9kfQHuqyTs4ik2eVbpvtinfCBT68LZ71ST2Ad0WBEGrBptTIkjD5ph8t3wadTuA/2+JvWA4EuZvJhcy3oxNatvE+rl7zWLhW+y/EPOjLE4POZ4brQfg9GwkDy99oqdCQeSsh5tax3romd1WL+6pO4wgc7kX2oi0kO1KCv5iHZNC4UuFRhMCS1lmwULJ8dOBIZffCaWkxkb2Rod4=
